
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qeuzosggikxwnpyhulox.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFldXpvc2dnaWt4d25weWh1bG94Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5NzMwMDAsImV4cCI6MjA1OTU0OTAwMH0.6ebEh2HRX9YJlRjvKXKeybMnfnEXxfgwXbGtHhaDcQs";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: false, // Keep this false to prevent redirect issues
    storage: localStorage,
    flowType: 'pkce',
    debug: true // Maintain debug mode to help with troubleshooting
  }
});
